#       ----------- + CryptoCurrency by Ziga Zajc + -----------   #
#                                                                 #
#                               Config                            #
#                                                                 #
#       ----------- + --------------------------- + -----------   #
#
#       You can use chat colors:
#                ________________________
#               |   code: | color:       |
#               |________________________|
#               |     &0  |	Black	     |
#               |     &1  |	Dark Blue	 |
#               |     &2  |	Dark Green	 |
#               |     &3  |	Dark Aqua	 |
#               |     &4  |	Dark Red	 |
#               |     &5  |	Dark Purple	 |
#               |     &6  |	Gold	     |
#               |     &7  |	Gray	     |
#               |     &8  |	Dark Gray	 |
#               |     &9  |	Blue	     |
#               |     &a  |	Green	     |
#               |     &b  |	Aqua	     |
#               |     &c  |	Red	         |
#               |     &d  |	Light Purple |
#               |     &e  |	Yellow	     |
#               |     &f  |	White	     |
#               |     &k  |	Obfuscated	 |
#               |     &l  |	Bold	     |
#               |     &m  |	Strikethrough|
#               |     &n  |	Underline	 |
#               |     &o  |	Italic	     |
#               |     &r  |	Reset	     |
#               |________________________|
#
#----------------------------------------------------------
#                        Config
#----------------------------------------------------------
# Players will see messages in default language (Default is English) - Available options: English.
# If you translate plugin into any other language feel free to send it and I will include it into this plugin.
default_language: "English"
# Money decimal format
money_format: "##,###.00"
# You can choose between:
# AED, AFN, ALL, AMD, ANG, AOA, ARS, AUD, AWG, AZN, BAM, BBD, BDT, BGN, BHD, BIF, BMD, BND, BOB, BRL,
# BSD, BTN, BWP, BYN, BYR, BZD, CAD, CDF, CHF, CLF, CLP, CNH, CNY, COP, CRC, CUC, CVE, CZK, DJF, DKK,
# DOP, DZD, EGP, ERN, ETB, EUR, FJD, FKP, GBP, GBX, GEL, GGP, GHS, GIP, GMD, GNF, GTQ, GYD, HKD, HNL,
# HRK, HTG, HUF, IDR, ILS, IMP, INR, IQD, ISK, JEP, JMD, JOD, JPY, KES, KGS, KHR, KMF, KRW, KWD, KYD,
# KZT, LAK, LBP, LKR, LRD, LSL, LYD, MAD, MDL, MGA, MKD, MMK, MNT, MOP, MRO, MTL, MUR, MVR, MWK, MXN,
# MYR, MZN, NAD, NGN, NIO, NOK, NPR, NZD, OMR, PAB, PEN, PGK, PHP, PKR, PLN, PYG, QAR, RON, RSD, RUB,
# RWF, SAR, SBD, SCR, SEK, SGD, SHP, SLL, SOS, SRD, SSP, STD, SVC, SZL, THB, TJS, TMM, TMT, TND, TOP,
# TRY, TTD, TWD, TZS, UAH, UGX, USD, UYU, UZS, VES, VND, VUV, WST, XAF, XAG, XAU, XCD, XDR, XOF, XPD,
# XPF, XPT, YER, ZAR, ZMW, ZWL
api_currency: "USD"
# After how many minutes plugin will fetch data from Coinbase again (Gets crypto values)
price_fetch: 1
#----------------------------------------------------------
#                        BTC API
#----------------------------------------------------------
# Btc decimal format
btc_format: "0.0000"
# Maximum BTC players can send, buy or sell.
btc_maximum: 100
# Minimum BTC players can send, buy or sell.
btc_minimum: 0.0001
#----------------------------------------------------------
#                        BCH API
#----------------------------------------------------------
# Bch decimal format
bch_format: "0.0000"
# Maximum BCH players can send, buy or sell.
bch_maximum: 10000
# Minimum BCH players can send, buy or sell.
bch_minimum: 0.0001
#----------------------------------------------------------
#                        ETH API
#----------------------------------------------------------
# Eth decimal format
eth_format: "0.000"
# Maximum ETH players can send, buy or sell.
eth_maximum: 5000
# Minimum ETH players can send, buy or sell.
eth_minimum: 0.001
#----------------------------------------------------------
#                        ETC API
#----------------------------------------------------------
# Etc decimal format
etc_format: "0.000"
# Maximum ETC players can send, buy or sell.
etc_maximum: 100000
# Minimum ETC players can send, buy or sell.
etc_minimum: 0.001
#----------------------------------------------------------
#                        DOGE API
#----------------------------------------------------------
# Doge decimal format
doge_format: "0.000"
# Maximum DOGE players can send, buy or sell.
doge_maximum: 1000000
# Minimum DOGE players can send, buy or sell.
doge_minimum: 0.001
#----------------------------------------------------------
#                        LTC API
#----------------------------------------------------------
# Ltc decimal format
ltc_format: "0.000"
# Maximum LTC players can send, buy or sell.
ltc_maximum: 10000
# Minimum LTC players can send, buy or sell.
ltc_minimum: 0.001
#----------------------------------------------------------
#                       USDT API
#----------------------------------------------------------
# Usdt decimal format
usdt_format: "0.00"
# Maximum USDT players can send, buy or sell.
usdt_maximum: 1000000
# Minimum USDT players can send, buy or sell.
usdt_minimum: 0.01
#----------------------------------------------------------
#                        Bungeecord
#----------------------------------------------------------
# Do you want to use mysql database?
mysql: false
# Here are all data for connection to Mysql database. Please create database, user and password by yourself. Do not use root as user, because of security risk!
mysql_host: "localhost"
mysql_port: "3306"
mysql_database: "CryptoCurrency"
mysql_user: "root"
mysql_password: ""
mysql_useSSL: false