#       ----------- + CryptoCurrency by Ziga Zajc + -----------   #
#                                                                 #
#                               Config                            #
#                                                                 #
#       ----------- + --------------------------- + -----------   #
#
#       You can use chat colors:
#                ________________________
#               |   code: | color:       |
#               |________________________|
#               |     &0  |	Black	     |
#               |     &1  |	Dark Blue	 |
#               |     &2  |	Dark Green	 |
#               |     &3  |	Dark Aqua	 |
#               |     &4  |	Dark Red	 |
#               |     &5  |	Dark Purple	 |
#               |     &6  |	Gold	     |
#               |     &7  |	Gray	     |
#               |     &8  |	Dark Gray	 |
#               |     &9  |	Blue	     |
#               |     &a  |	Green	     |
#               |     &b  |	Aqua	     |
#               |     &c  |	Red	         |
#               |     &d  |	Light Purple |
#               |     &e  |	Yellow	     |
#               |     &f  |	White	     |
#               |     &k  |	Obfuscated	 |
#               |     &l  |	Bold	     |
#               |     &m  |	Strikethrough|
#               |     &n  |	Underline	 |
#               |     &o  |	Italic	     |
#               |     &r  |	Reset	     |
#               |________________________|
#
#----------------------------------------------------------
#                        Config
#----------------------------------------------------------
# Players will see messages in default language (Default is English) - Available options: English.
# If you translate plugin into any other language feel free to send it and I will include it into this plugin.
default_language: "English"
# Money decimal format
money_format: "##,###.00"
# You can choose between: USD, AUD, BRL, CAD, CHF, CLP, CNY, DKK, EUR, GBP, HKD, INR, ISK, JPY, KRW, NZD, PLN, RUB, SEK, SGD, THB and TWD.
api_currency: "USD"
# After how many minutes plugin will fetch data from Coinbase again (Gets crypto values)
price_fetch: 1
#----------------------------------------------------------
#                        BTC API
#----------------------------------------------------------
# Btc decimal format
btc_format: "0.0000"
# Minimum BTC players can send, buy or sell.
btc_minimum: 0.0001
#----------------------------------------------------------
#                        ETH API
#----------------------------------------------------------
# Eth decimal format
eth_format: "0.000"
# Minimum ETH players can send, buy or sell.
eth_minimum: 0.001
#----------------------------------------------------------
#                        Bungeecord
#----------------------------------------------------------
# Do you want to use mysql database?
mysql: false
# Here are all data for connection to Mysql database. Please create database, user and password by yourself. Do not use root as user, because of security risk!
mysql_host: "localhost"
mysql_port: "3306"
mysql_database: "CryptoCurrency"
mysql_user: "root"
mysql_password: ""
mysql_useSSL: false