name: CryptoCurrency
version: ${project.version}
main: com.rabbitcompany.CryptoCurrency
api-version: 1.13
softdepend: [Vault]
authors: [Black1_TV]
description: Take crypto world into MInecraft
website: https://rabbit-company.com
commands:
  btc:
    usage: /<command>
    description: Manage with bitcoin
  bch:
    usage: /<command>
    description: Manage with bitcoin cash
  eth:
    usage: /<command>
    description: Manage with ethereum
  etc:
    usage: /<command>
    description: Manage with ethereum classic
  doge:
    usage: /<command>
    description: Manage with dogecoin
  ltc:
    usage: /<command>
    description: Manage with litecoin
  usdt:
    usage: /<command>
    description: Manage with tether